title: Store Framework
tagline: A brand new course on Learning Lab
description: >-
  Learning how to build a store using the Store Framework blocks language,
  powered by VTEX IO.
template:
  repo: store-framework-template
  name: store-framework
before:
  - type: createIssue
    title: Store Framework 101
    body: step-0.md
steps:
  - title: Store Framework 101
    description: Quick introduction definitions.
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: new-issue.md
        issue: 1
        data:
          nextIssue: '2'
          nextName: 'First block: Info Card'
      - type: createIssue
        title: 'First block: Info Card'
        body: step-1.md
  - title: 'First block: Info Card'
    description: Compose and reference your first store framework block
    event: status
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 2
        data:
          nextIssue: '3'
          nextName: Making the info card slide
      - type: createIssue
        title: Making the info card slide
        body: step-2.md