title: Store Framework
tagline: A brand new course on Learning Lab
description: >-
  Learning how to build a store using the Store Framework blocks language,
  powered by VTEX IO.
template:
  repo: store-framework-template
  name: store-framework
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Assign yourself
    description: Assign the first issue to yourself.
    event: status
    link: '{{ repoUrl }}/issues/1'
    actions:
    - type: respond
      with: new-issue.md
      issue: 1