title: Store Framework
tagline: A brand new course on Learning Lab
description: >-
  Learning how to build a store using the Store Framework blocks language,
  powered by VTEX IO.
template:
  repo: store-framework-template
  name: store-framework
before:
  - type: createIssue
    title: Funcionamento do curso
    body: step-minus1.md
steps:
  - title: Funcionamento do curso
    description: Explicando como interagir com o curso.
    event: issues.closed
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: respond
        with: new-issue.md
        issue: 1
        data:
          nextIssue: '2'
          nextName: 'Store Framework 101'
      - type: createIssue
        title: 'Store Framework 101'
        body: step-0.md
  - title: Store Framework 101
    description: Definições rápidas e introdutórias sobre o Store Framework.
    event: issues.closed
    link: '{{ repoUrl }}/issues/2'
    actions:
      - type: respond
        with: new-issue.md
        issue: 2
        data:
          nextIssue: '3'
          nextName: 'Hello, World!'
      - type: createIssue
        title: 'Hello, World!'
        body: step-1.md
  - title: Hello, World!
    description: Componha e referencie seu primeiro bloco no Store Framework
    event: status
    link: '{{ repoUrl }}/issues/3'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 3
        data:
          nextIssue: '4'
          nextName: 'Info Card: o call to action do Store Framework'
      - type: createIssue
        title: 'Info Card: o call to action do Store Framework'
        body: step-2.md
  - title: 'Info Card: o call to action do Store Framework'
    description: Definiremos um bloco call to action na nossa home
    event: status
    link: '{{ repoUrl }}/issues/4'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 4
        data:
          nextIssue: '5'
          nextName: Estilizando o Info Card
      - type: createIssue
        title: Estilizando o Info Card
        body: step-3.md
  - title: 'Shelf - A prateleira de produtos'
    description: Vamos usar o componente `shelf` para implementar uma prateleira de produtos
    event: status
    link: '{{ repoUrl }}/issues/7'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 7
        data:
          nextIssue: '8'
          nextName: Slider Layout - criando sliders de conteúdo
      - type: createIssue
        title: Slider Layout - criando sliders de conteúdo
        body: step-6.md