title: Store Framework
tagline: A brand new course on Learning Lab
description: >-
  Learning how to build a store using the Store Framework blocks language,
  powered by VTEX IO.
template:
  repo: store-framework-template
  name: store-framework
before:
  - type: createIssue
    title: Shelf
    body: step-1.md
steps:
  - title: Assign yourself
    description: Assign the first issue to yourself.
    event: status
    link: '{{ repoUrl }}/issues/1'
    actions:
      - type: gate
        left: '%payload.state%'
        operator: ===
        right: success
      - type: respond
        with: new-issue.md
        issue: 1
        data:
          nextIssue: '2'
          nextName: Coisa linda
      - type: createIssue
        title: Carousel
        body: step-1.md